sim: rewrite memory-region overlapping helper
problem:
  when the following memory region is specified
  -m0x00410000:0x1000,
    0x00410200:0x1000,
    0x00410400:0x1000,
    0x00410600:0x1000,
    0x00410800:0x1000,
    0x00411000:0x1000,
    0x00412000:0x1000,
    0x00413000:0x1000,
    0x00414000:0x1000

  The error is
    ERROR (duplicate_node_names): Duplicate node name /memory@410
    ERROR (duplicate_node_names): Duplicate node name /memory@410
    ERROR (duplicate_node_names): Duplicate node name /memory@410
    ERROR (duplicate_node_names): Duplicate node name /memory@410
    ERROR (duplicate_node_names): Duplicate node name /memory@410
    ERROR (duplicate_node_names): Duplicate node name /memory@410
    ERROR: Input tree has errors, aborting (use -f to force output)

cause:
  the merge_overlapping_memory_regions works not well in partial overlap case

change:
   1. use forward way to avoid weird reverse iterator behavior in C++
   2. use address but not page number since the base addresses are
      all aligned in make_mems

Signed-off-by: Chih-Min Chao <chihmin.chao@sifive.com>